# Generated by Django 4.1 on 2022-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_descuento',
            field=models.FloatField(null=True),
        ),
    ]
