# Generated by Django 4.1 on 2022-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacados_semanales',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_nuevo',
            field=models.BooleanField(null=True),
        ),
    ]
